local wk = require "which-key"

wk.add {
  {
    "<leader>;",
    "<cmd>lua require('Comment.api').toggle.linewise.current()<CR>",
    desc = "Comment",
  },
  { "<leader>a", group = "Search" },
  { "<leader>ab", "<cmd>Telescope buffers<CR>", desc = "Search Buffer" },
  { "<leader>ag", "<cmd>Telescope live_grep<CR>", desc = "Search Keyword" },
  { "<leader>b", group = "Buffer" },
  { "<leader>bk", ":bw<CR>", desc = "Kill Buffer" },
  { "<leader>d", group = "Debugger" },
  { "<leader>dP", desc = "Clear All BreakPoints" },
  { "<leader>dc", desc = "Continue" },
  { "<leader>dh", desc = "Help" },
  { "<leader>di", desc = "Step Into" },
  { "<leader>dj", desc = "Step Over" },
  { "<leader>do", desc = "Step Out" },
  { "<leader>dp", desc = "Set BreakPoint" },
  { "<leader>dq", desc = "Quit" },
  { "<leader>ds", desc = "Start" },
  { "<leader>dt", desc = "Toggle Debugger View" },
  { "<leader>f", group = "File" },
  { "<leader>fc", "<cmd>NvimTreeCollapse<CR>", desc = "Tree Collapse" },
  { "<leader>fd", "<cmd>NvimTreeFocus<CR>", desc = "Find Current File" },
  { "<leader>fr", "<cmd>NvimTreeRefresh<CR>", desc = "Tree Refresh" },
  { "<leader>fs", ":update<CR>", desc = "Save" },
  { "<leader>ft", "<cmd>NvimTreeToggle<CR>", desc = "Toggle Tree" },
  { "<leader>g", group = "gitsigns" },
  { "<leader>gD", desc = "Diff This ~" },
  { "<leader>gR", desc = "Reset Buffer" },
  { "<leader>gS", desc = "Stage Buffer" },
  { "<leader>gb", desc = "Blame Line" },
  { "<leader>gd", desc = "Diff This" },
  { "<leader>gp", desc = "Preview Hunk" },
  { "<leader>gr", desc = "Visual Reset Hunk" },
  { "<leader>gs", desc = "Stage Hunk" },
  { "<leader>gt", desc = "Toggle Current Line Blame" },
  { "<leader>gu", desc = "Undo Stage Hunk" },
  { "<leader>gx", desc = "Toggle Deleted" },
  { "<leader>l", group = "LSP" },
  { "<leader>lc", desc = "Code Action" },
  { "<leader>lo", "<cmd>Lspsaga outline<CR>", desc = "Toggle Outline" },
  { "<leader>lr", "<cmd>Lspsaga rename<CR>", desc = "Rename" },
  { "<leader>p", group = "Projects" },
  {
    "<leader>pt",
    "<cmd>Telescope projects<CR>",
    desc = "Show Recent Projects",
  },
  -- { "<leader>s", group = "Search" },
  -- { "<leader>sc", ":nohlsearch<CR>", desc = "Clear Highlight Result" },
  { "<leader>t", group = "Terminal" },
  { "<leader>w", group = "Window" },
  { "<leader>w=", "<C-w>=", desc = "Same Width Split Window" },
  { "<leader>wc", "<C-w>c", desc = "Close Current Window" },
  { "<leader>wh", ":vsp<CR>", desc = "Split Horizontal Window" },
  { "<leader>wo", "<C-w>o", desc = "Close Other Windows" },
  { "<leader>wv", ":sp<CR>", desc = "Split Vertical Window" },
}

wk.add {
  {
    "<localleader>=",
    "<cmd>lua vim.lsp.buf.format{ async = true }<CR>",
    desc = "Formatting",
  },
  { "<localleader>s", group = "Swift" },
  { "<localleader>c", desc = "Change Background" },
  { "<localleader>d", group = "Diagnostic" },
  { "<localleader>dd", desc = "Show Line Diagnostic By Vim API" },
  { "<localleader>dl", desc = "Show Line Diagnostic" },
  { "<localleader>dn", desc = "Show Next Diagnostic" },
  { "<localleader>dp", desc = "Show Prev Diagnostic" },
  { "<localleader>dw", desc = "Show Cursor Diagnostic" },
  { "<localleader>e", "<cmd>Telescope buffers<CR>", desc = "Show Buffers" },
  { "<localleader>k", "<cmd>bd<CR>", desc = "Delete Buffer" },
  { "<localleader>l", group = "Lsp" },
  { "<localleader>lr", "<cmd>LspRestart<CR>", desc = "Lsp Restart" },
  { "<localleader>n", "<cmd>NerdIcons<CR>", desc = "Open Nerd Icons" },
  { "<localleader>o", "<cmd>Telescope find_files<CR>", desc = "Open File" },
  { "<localleader>t", group = "Quickfix List" },
  {
    "<localleader>tt",
    "<cmd>Lspsaga term_toggle<CR>",
    desc = "Toggle Terminal",
  },
  {
    "<localleader>tb",
    "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
    desc = "Buffer Diagnostics (Trouble)",
  },
  {
    "<localleader>tx",
    "<cmd>Trouble diagnostics toggle focus=true<cr>",
    desc = "Diagnostics (Trouble)",
  },
}

wk.setup {
  preset = "modern",
  icons = {
    breadcrumb = "»", -- symbol used in the command line area that shows your active key combo
    separator = "➜", -- symbol used between a key and it's label
    group = "+", -- symbol prepended to a group
  },
  win = { border = "single" },
  layout = {
    width = { min = 20 },
    spacing = 3,
  },
  triggers = {
    { "<leader>", mode = "n" },
    { "<localleader>", mode = "n" },
  },
}
